# -*- coding: utf-8 -*-
"""EDC Fetch and Push From RSS FEED

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NAOpas881KZD2h8BagToMvPapKWtixRV

#### Install Required Packages
"""

!pip install feedparser # Installs the required packages
import feedparser

"""#### Code to Parse The Feed"""

# URL of the RSS feed
feed_url = "Enter URL Here" + "/feed"

# example : "https://ecelluiet.substack.com" + "/feed"


# Parse the RSS feed
feed = feedparser.parse(feed_url)

# Check if the feed has entries
if feed.entries:
    first_item = feed.entries[0]

    # Extracting details from the first item
    title = first_item.title if 'title' in first_item else 'No title'
    description = first_item.description if 'description' in first_item else 'No description'
    link = first_item.link if 'link' in first_item else 'No link'
    content = first_item.content[0].value if 'content' in first_item and first_item.content else 'No content'

# title, description, link, content

"""#### Saving to a Markdown File"""

import time
from tqdm import tqdm
# File name for the Markdown file
markdown_file = "output.md"

# Open the file in write mode
with open(markdown_file, 'w') as file:
    # Writing data to the file in Markdown format
    file.write(f"# {title}\n\n")  # Title in H1
    file.write(f"**Description:** {description}\n\n")  # Description in bold
    file.write(f"[Link]({link})\n\n")  # Hyperlink
    file.write("## Content\n")  # Content Header
    file.write(f"{content}\n")  # Content

# Duration of your sleep, in seconds
sleep_duration = 30

# Using tqdm to show a progress bar
for _ in tqdm(range(sleep_duration), desc="Ensuring Generation of File"):
    time.sleep(1)  # Sleep for 1 second at a time

print(f"Data written to {markdown_file}")